### ISSUE TITLE
Parser.cs file incorrectly parses embedded Div tags

### ISSUE THREAD

**Issue by Ryan-George** [FairfieldTekLLC/Hocr#1]
Great job on this project!  I'm finding it very useful!  I did find a bug, though and wanted to report it.

I was chasing a bug where the resulting pdf that gets rebuilt from the split hocr files has an output that doubles up the text on a page.  You don't see it in the pdf, but if you extract the text from the final pdf and look through it, I would often see the text repeated.  What I found was the problem lay in how the div nodes are grabbed.  

In many of the hocr files I was working with, inside the body tag, there was a div tag that then encapsulated the rest of the body of the page.  All the other div tags were inside that initial one.  When grabbing the div tags, the line below grabs all div tags and puts them in a collection of nodes:
`HtmlNodeCollection nodes = body.SelectNodes("//div");`

This is pretty efficient, but the first div tag, in my scenario, had child elements that made up the rest of the page. Since it contains all the other div tags, and those embedded div tags are also collected into the NodeCollection, all those embedded div tags are repeated in the resulting node parsing code.  The node collection from that line above does not take into account the hierarchy of the nodes. It just grabs all the matching nodes and gives you a collection of them.

My fix was to change the above code line to this:
`var divs = body.ChildNodes.Where(node => node.Name.ToLower() == "div");`
 `HtmlNodeCollection nodes = new HtmlNodeCollection(null);`
 `foreach (var div in divs) { nodes.Add(div); }`

This code then only grabbed the div tag nodes of the child nodes of the body tag.  In my case it was one div node.  I then created a collection and parsed that collection. Since the child nodes are also parsed, then everything got parsed once and there weren't any repeats.

I've included an example hocr file for reference. I had to change the extension to txt so I could upload it, 

[example.txt](https://github.com/FairfieldTekLLC/Hocr/files/2520169/example.txt)

**Comment by FairfieldTekLLC** [comment]
Would it be possible for you to do a pull request on this?

**Comment by FairfieldTekLLC** [comment]
I'm testing the fix now, I found where you were talking about it.  Should have it merged shortly if the tests look good.

**Comment by FairfieldTekLLC** [comment]
Fix is in the code, thanks for posting it!

**Comment by Ryan-George** [comment]
Thanks!  I got to this after you fixed it. If I find anything else I'll do a pull request =)

Great project!
